In [8]:
import numpy as np
import scipy.misc
import matplotlib.pyplot as plt

# Overview of features

In [34]:
#Load features (.npy)
path = '/media/nejc/Prostor/AI/data/test_arranged_class_labels/'
filename = '02'
every = 10
features = np.load(path + filename + '.npy')
imgs = list(features[:,0])
labels = list(features[:,1])

In [35]:
for label in labels:
    print label


[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]


In [30]:
n=0
for img, label in zip(imgs, labels):
    n += 1
    if n % every == 0:
        fig = plt.figure()
        plt.title(label)
        plt.imshow(img)